# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]
  push:
    branches:
      - master    

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip wheel
        pip install setuptools twine
    - name: Run tests
      env:
        CODECOV_TOKEN:  ${{ secrets.CODECOV_TOKEN }}
      run: |
        pip install pytest
        pip install pytest-cov
        pip install codecov
        pytest --cov-report=html --cov-report=annotate --cov=./BitParser test
        pwd
        ls -la
        codecov -t ${{ secrets.CODECOV_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: coverage.xml
        path: /home/runner/work/bit-parser/bit-parser/coverage.xml
    - uses: actions/upload-artifact@v2
      with:
        name: htmlcov
        path: '/home/runner/work/bit-parser/**/*htmlcov*'
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        CODECOV_TOKEN:  ${{ secrets.CODECOV_TOKEN }}
      run: |
        python ./pypi/setup.py sdist bdist_wheel
        twine upload dist/*
